### ISSUE TITLE
RippleImageButton

### ISSUE THREAD

**Issue by fiskurgit** [xgc1986/RippleButton#1]
Would be great to be able to have an RippleImageButton too - so I can style my icon'd buttons the same as my text buttons. Thanks for what you've done so far though, it's great.

**Comment by xgc1986** [comment]
Ok, I just upload a new version, this have RippleImageButton.

`compile 'com.xgc1986.android:ripplebutton:0.3.0'`

If you have another views that you want to have this effect, in version 0.2.0 I created RippleDrawableHelper that returns a drawable with the effect (on >= 21) or only changes the color ( < 21) of the view

``` java
// you can uset on API 10+ without worry the android version
Drawable myDrawable = RippleDrawableHelper.createRippleDrawable(myView, viewColor, rippleColor);
```

I upload the apk of the sample, here I use this class to create the buttons drawables of each card, one is a LinearLayout and the other is a Textview

**Comment by fiskurgit** [comment]
Works perfectly - thank you!
